name: Daily Reflection

on:
  schedule:
    - cron: '15 21 * * *'
    - cron: '07 8 * * *'
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install wordfreq

      - name: Send daily reflection
        env:
          EMAIL_FROM:      ${{ secrets.EMAIL_FROM }}
          EMAIL_TO:        ${{ secrets.EMAIL_TO }}
          SMTP_SERVER:     ${{ secrets.SMTP_SERVER }}
          SMTP_PORT:       ${{ secrets.SMTP_PORT }}
          EMAIL_USERNAME:  ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD:  ${{ secrets.EMAIL_PASSWORD }}
        run: python main.py
